kubewarden/policy-evaluator

src/policy_metadata.rs
If policy labels are not provided in the policy metadata, assume no
labels and default to None.
=> Make metadata labels optional

Cargo.lock, Cargo.toml, src/policy_metadata.rs
Introduce the optional field 'annotatedBy', this can be used to track  which program added the metadata to the final Wasm file.
This can be used to debug issues with policies.
=> Policy metadata introduce `annotatedBy`

Cargo.toml, src/cluster_context.rs, src/lib.rs, src/policy_metadata.rs
The crate library will not start a refresh loop, and will let up to
the caller to refresh the context aware structure when it wants.
Related: https://github.com/kubewarden/kwctl/issues/40
=> refactor: context awareness

src/constants.rs, src/lib.rs, src/policy.rs, src/policy_evaluator.rs, src/policy_metadata.rs, src/policy_tracing.rs
Implement a waPC `kubewarden.tracing.log` host function.
Co-authored-by: Flavio Castelli <fcastelli@suse.com>
=> feat: implement policy logging

src/policy_evaluator.rs, src/policy_metadata.rs
Enrich the policy metadata with a new field that explains which execution mode (kubewarden, opa, gatekeeper) must be used to evaluate the policy.
By default, when nothing is specified, we fall back to the kubewarden execution mode.
Note well, I reused the `PolicyExecutionMode` enum to identify the type of execution mode to be used. That forced me to implement a custom serializer and deserializer for the enum. That introduces some extra code (especially the deserialization bit), but that's how serde wants things to be done.
=> Add policy execution mode to metadata

src/policy_evaluator.rs, src/policy_metadata.rs
This is required to automatically fall-back to the Kubewarden evaluation mode when looking at `metadata.yml` files.
=> Implement Default trait for PolicyExecutionMode

src/policy_metadata.rs
The Metadata validation rules must take into account how the Opa/Gatekeeper policies behave.
The protocol version is allowed to be "unknown" for them.
=> Update Metadata validation rules

crates/burrego/examples/dataless-inputless-bundle/.gitignore, crates/burrego/examples/dataless-inputless-bundle/Makefile, crates/burrego/examples/dataless-inputless-bundle/accept.rego, crates/burrego/examples/dataless-inputless-bundle/reject.rego
This rego policies have everything hardcoded and do not depend on
`data` nor `input`.
=> examples: add basic example rego policies

crates/burrego/src/main.rs, crates/burrego/src/opa/default_host_callbacks.rs, crates/burrego/src/opa/host_callbacks.rs, crates/burrego/src/opa/mod.rs, crates/burrego/src/opa/wasm.rs, src/runtimes/burrego.rs
This PR is built on top of https://github.com/kubewarden/policy-evaluator/pull/34 and supersede it.
Differences introduced by this PR:
* `opa_abort`
* Fix how the error message of `opa_abort` is retrieved from the Wasm memory
* Do not cause the running process to exit immediately with an error. An `Err` is automatically raised by Wasmtime. The same Wasmtime stack (engine, instance, memory,...) can be reused to process more requests
=> Opa callbacks

crates/burrego/Cargo.toml, crates/burrego/src/opa/builtins/mod.rs, crates/burrego/src/opa/builtins/regex.rs, src/policy_evaluator.rs
Related: https://github.com/kubewarden/policy-evaluator/issues/38
Implements the following builtins:
- `regex.split`
- `regex.template_match`
- `regex.find_n`
From this group, `regex.globs_match` is left unimplemented due to the
ratio effort/benefit and lack of real world consumers.
=> Implement regex builtins

crates/burrego/Cargo.toml, crates/burrego/src/opa/builtins/mod.rs, crates/burrego/src/opa/builtins/semver.rs
Fixes https://github.com/kubewarden/policy-evaluator/issues/50
=> Implement semver builtins

crates/burrego/src/opa/builtins/glob.rs, crates/burrego/src/opa/builtins/mod.rs
Fixes: https://github.com/kubewarden/policy-evaluator/issues/39
=> Implement glob builtins

crates/burrego/src/opa/builtins/encoding.rs, crates/burrego/src/opa/builtins/mod.rs
This is part of the `encoding` built-in group
=> burrego: implement `yaml.is_valid` builtin

Cargo.toml, src/callback_handler/mod.rs, src/callback_handler/oci.rs, src/callback_requests.rs, src/lib.rs, src/policy.rs, src/policy_evaluator.rs, src/policy_evaluator_builder.rs, src/runtimes/wapc.rs
Expose the get OCI manifest digest callback
Allow the Wasm guests to obtain the manifest's digest of
an OCI object (be it a container or an artifact).
Fetching information from a OCI registry requires the execution
of asynchronous code. Unfortunately the `host_callback` function
is a synchronous function.
Creating a dedicated tokio runtime (even by reusing the "current thread"
of the `host_callback` function) is not going to work. This would cause
tokio to cause a `panic` at runtime.
The solution of this problem consists of using a tokio channel that can
send the evaluation request from the synchronous world (the `host_callback`
function) to an `asynchronous` "worker" (something created with a tokio
`spawn` for example).
The response from the asynchronous world is then sent back to the …
=> Expose "get OCI manifest digest" callback

crates/burrego/src/main.rs, src/lib.rs
This makes easier for consumers of both crates (e.g. `kwctl` and
`policy-server`) to consume types and traits that are common to
both (given that `policy-evaluator` also depends on `policy-fetcher`).
=> Expose `policy-fetcher` through `policy-evaluator`

crates/burrego/src/main.rs, crates/burrego/src/opa/wasm.rs
This is required to dump the list of entrypoints a Rego Wasm module has.
=> burrego: expose the `entrypoints` API

Cargo.toml
Bumps the policy-evaluator to version v0.2.18. This version updates the kube crate.
=> Bump v0.2.18 version.

Cargo.toml, src/callback_handler/mod.rs, src/callback_handler/sigstore.rs, src/callback_handler/sigstore_verification.rs, src/callback_requests.rs, src/lib.rs, src/policy_evaluator.rs, src/policy_metadata.rs, src/runtimes/burrego.rs, src/runtimes/wapc.rs, src/validation_response.rs
` v1/verify` operation added which can be called from the sdk to verify sigstore signatures for a given image. This new operation will receive a CallbackRequestType  which can be SigstorePubKeyVerify and SigstoreKeylessVerify. Verification results are cached for 60 seconds.
Fix https://github.com/kubewarden/policy-server/issues/99
=> feat: Allow policy authors to write policies that perform image verification

Cargo.toml, src/callback_handler/mod.rs, src/callback_handler/sigstore_verification.rs, src/callback_requests.rs, src/lib.rs, src/policy_evaluator.rs, src/policy_metadata.rs, src/runtimes/burrego.rs, src/runtimes/wapc.rs, src/validation_response.rs
Do not consume the policy SDK via policy-fetcher, this is a leftover from one of the old iterations of the Sigstore integration.
Starting from v0.7.1 of policy-fetcher, the policy SDK is no longer re-exposed by policy-fetcher.
The policy SDK belongs to the policy-evaluator.
Depends on https://github.com/kubewarden/policy-fetcher/pull/83
I'll update this PR once the one against policy-fetcher gets merged
=> Fix policy SDK dependency graph

Cargo.toml, crates/burrego/src/main.rs, src/callback_handler/mod.rs, src/callback_handler/oci.rs, src/runtimes/wapc.rs
This PR extents the waPC capabilities offered to our policy authors by introducing a new API that allows reverse DNS lookup.
This fixes https://github.com/kubewarden/policy-server/issues/236
While working on this PR, I also realized the "OCI get manifest invocations" were not encoding and decoding the waPC payload properly.
=> add wapc dns lookup callback

Cargo.toml, src/policy_metadata.rs
The API changed, hence some pieces of our code had to be refactored.
This supersedes https://github.com/kubewarden/policy-evaluator/pull/126
=> Update to latest wasmparser release

Cargo.toml, src/policy_evaluator.rs, src/policy_evaluator_builder.rs
Allow usage of Wasmtime cache feature. This reduces significantly the load time of a policy once the cache has been warmed up.
By default this feature is disable, leading the old behaviour unchanged.
I've will tag a new patch release of policy-evaluator once this PR is merged.
=> Allow usage of Wasmtime cache

Cargo.toml, src/admission_response.rs, src/lib.rs, src/policy_evaluator.rs, src/runtimes/burrego.rs, src/runtimes/wapc.rs
Rename the `ValidationResponse` object to be `AdmissionResponse`. This uses the same terminology of Kubernetes. This is needed later on, inside of policy-server, when building proper AdmissionResponse `Response` objects.
While using the `AdmissionResponse`, make use of the fields that have been just exposed by the Rust policy SDK. This ensures we can create any kind of AdmissionResponse that Kubernetes supports.
=> use admission response

Cargo.toml, src/admission_response.rs, src/runtimes/wapc.rs
Handle DELETE operations
DELETE operations have a null 'object' inside of the 'request'.
This removes the old validation we had in place that actually prevented the creation of policies dealing with DELETE operations.
This code introduces a check to ensure a policy author doesn't attempt a mutation operation when a DELETE happens.
While working on that, I discovered we were requiring the hyper crate. The hyper dependency was used only to access a constant definig the HTTP status of for internal server error.
That was quite an overkill...
=> handle delete operations

Cargo.toml, src/callback_handler/mod.rs, src/callback_handler/sigstore_verification.rs, src/runtimes/wapc.rs
Consume deambiguation of KeylessPrefix request.
Support v2/verify callbacks.
=> Consume SDK 0.6.2 for `v2/verify`

Cargo.toml, crates/burrego/Cargo.toml, src/policy_evaluator.rs
Consume the lastest versions of wasmtime. The waPC provider is now exporting the version of wasmtime it depends against, which simplifies our `Cargo.toml` file.
=> Update to latest stable release of wasmtime

Cargo.toml, src/callback_handler/mod.rs, src/callback_requests.rs, src/runtimes/wapc.rs
Move CallbackRequestType from policy-sdk to policy-evaluator. Consume SigstoreVerificationInputV1 and SigstoreVerificationInputV2 for verification callbacks.
Relates https://github.com/kubewarden/policy-sdk-rust/issues/40
Relates https://github.com/kubewarden/policy-sdk-rust/issues/41
Tested locally with a local built policy
=> Add GitHub actions and subject prefix 

Cargo.toml, src/callback_handler/mod.rs, src/callback_handler/sigstore_verification.rs
Do not fail when Fulcio and Rekor data are None. The Sigstore integration will still work, but it will provide some false negatives.
False netative means: a perfectly valid signature produced with keyless mode will be reported as non valid.
This is currently required to handle the case when the upstream TUF repository of Sigstore is broken.
=> Allow fulcio and rekor data to be None

src/lib.rs
kwctl uses validator too. When the `validator` version between kwctl and policy-evaluator is not the same, there could be compilation errors. This happens when the validator API breaks, like during the 0.15 to 0.16 upgrade.
Currently we would have to bump `validator` inside of `policy_evaluator`, tag a new release and then update both the `validator` and the `policy_evaluator` versions inside of kwctl.
By re-exposing the `validator` crate via the `policy_evaluator` we make the maintenance task easier.
=> Expose the validator crate

Cargo.toml, crates/burrego/Cargo.toml
Update a bunch of outdated deps. This is built on top of https://github.com/kubewarden/policy-evaluator/pull/173 and fixes the errors reported.
| Package | Type | Update | Change |
|---|---|---|---|
| [anyhow](https://togithub.com/dtolnay/anyhow) | dependencies | patch | `1.0.60` -> `1.0.63` |
| [chrono](https://togithub.com/chronotope/chrono) | dependencies | patch | `0.4.20` -> `0.4.22` |
| [serde_json](https://togithub.com/serde-rs/json) | dependencies | patch | `1.0.83` -> `1.0.85` |
| [serde_yaml](https://togithub.com/dtolnay/serde-yaml) | dependencies | patch | `0.9.4` -> `0.9.10` |
| [wasmtime-provider](https://wapc.io) | dependencies | patch | `1.0.1` -> `1.1.0` |
---
<details>
<summary>dtolnay/anyhow</summary>
[Compare Source](https://togithub.com/dtolnay/anyhow/compare/1.0.62...1 …
=> Fix update all patch

Cargo.toml, src/policy_metadata.rs
Set its default in creation to true.
Set its default if missing to true.
Relates to https://github.com/kubewarden/kwctl/issues/331
Relates to https://github.com/kubewarden/kwctl/issues/330
Amended tests, added a new backwards compatibility one.
=> feat: Add `Metadata.background_audit`

Cargo.toml, src/callback_handler/mod.rs, src/callback_handler/sigstore_verification.rs, src/callback_requests.rs
Allow sigstore based verification to be done using a certificate provided by the user.
This is required to implement: https://github.com/kubewarden/verify-image-signatures/issues/39
**Note:** I'm currently using code from git branches, this is going to be changed as soon as everything gets merged
=> feat: implement sigstore cert verification

Cargo.toml, src/callback_handler/crypto.rs, src/callback_handler/mod.rs, src/runtimes/wapc.rs
Fix https://github.com/kubewarden/policy-evaluator/issues/200
Needs https://github.com/kubewarden/policy-sdk-rust/pull/69
Needs https://github.com/kubewarden/policy-sdk-rust/pull/71
Given a cert and a cert chain, verifies the validity of the cert against
the passed cert chain.
If no chain is passed, only the cert validity against the current time
is checked.
Add new module `callback_handler::crypto`, that implements the cert
verification.
Added new unit test for the callback request and response.
=> feat: Add callback `crypto/v1/is_certificate_trusted`

Cargo.toml, src/callback_handler/crypto.rs, src/callback_handler/mod.rs, src/runtimes/wapc.rs
Relates to https://github.com/kubewarden/verify-image-signatures/pull/47#discussion_r1034836373
Make `verify_certificate()`, return `Result<policy-evaluator::BoolWithReason>`. Response either returns:
* `Ok(BoolWithReason::True)`.
* `Ok(BoolWithReason::False((reason))` with ``reason` such as "cert not trusted by cert
chain", or "cert expired".
* `Err(e)`, with `e` such as "cert not in PEM format", or "not_after
datetime not in RFC 3339 format".
Bump version to 0.4.17
Unit tests amended.
=> fix!: Make `verify_certificate()`, return `Result<BoolWithReason>`, & bump version

Cargo.toml, crates/burrego/Cargo.toml, crates/burrego/src/evaluator.rs
The Wasmtime Linker failed the initialization of Rego-based policies when the timeout protection (epoch deadline) feature was turned on.
This happens because Rego policies share their memory with the host. Because of that, an initialization function is invoked by the Linker at instantiation time. This function takes care of setting up the whole environment.
Prior to this commit, this invocation would fail every time because the `wasmtime::Store` did not have any tick inside of it.
Just for reference, this behavior is explained [here](https://github.com/WebAssembly/tool-conventions/blob/main/Linking.md#start-section).
When looking at a Rego-based module, via `wasm-objdump`, the following output can be found (warning: function numbers change, based on the module):
The start section:
``` …
```
=> fix repo policies and timeout protection

Cargo.toml, crates/burrego/Cargo.toml, crates/burrego/examples/cli/main.rs, crates/burrego/src/evaluator.rs
Sometimes the evaluation of a burrego policy led to a policy evaluation timeout.
This happened because, some parts of the code, forgot to add some ticks into the `wasmtime::Store` before invoking a wasm functions.
While working on that, I saved some static Rego data into the evaluator (like the entrypoints and the used builtins). By doing that we further reduce the invocations of wasm functions.
This fixes https://github.com/kubewarden/policy-evaluator/issues/239
**Note:** once this is merged, I'll tag a new release of policy-evaluator and bump that inside of Policy Server
=> fix rego evaluation when timeout protection is enabled

Cargo.toml, src/policy.rs, src/policy_evaluator_builder.rs, src/policy_metadata.rs, src/runtimes/wapc.rs
Limit the k8s resources that can be requested by a policy
Starting from this commit each policy has a list of Kubernetes resources that is allowed to access.
Any attempt to access a non allowed resource is going to be blocked and reported via the system logs.
=> Limit the k8s resources that can be requested by a policy

Cargo.toml, src/policy_artifacthub.rs, src/policy_evaluator.rs
fix!: Serialize `ArtifactHubPkg{}` deterministically, by using a `BTreeMap{}` for the annotations. 
build: Bump version to 0.8.0.
build: Add Victor to authors.
By CI.
Needed for kwctl scaffold comparisons.
Alternative: Use [IndexMap](https://docs.rs/indexmap/latest/indexmap/map/struct.IndexMap.html), but then we add dependencies.
=> fix!: Serialize `ArtifactHubPkg{}` deterministically

src/callback_requests.rs
This is required by the context aware feature, more specifically by the new callback handler proxy
This PR depends on https://github.com/kubewarden/policy-sdk-rust/pull/83
The test suite will keep failing until this gets merged
=> refactor: derive Eq traits against some structs

Cargo.toml, src/policy_artifacthub.rs
Fill it with the OCI URL as we were doing so far. E.g:
The policy can be obtained using [`kwctl`](https://github.com/kubewarden/kwctl):
```console
kwctl pull ghcr.io/ocirepo/namespace/verify-image-signatures:v0.2.1
```
We forgot to fill this, looking at [the RFC](https://github.com/kubewarden/rfc/blob/main/rfc/0014-metadata.md).
This will need a new release to be consumed by kwctl in 1.6.0-rc3
Amended unit tests.
We could expand it with instructions to do a `kwctl scaffold clusteradmissionpolicy` or the like. I welcome suggestions.
=> feat: Set ArtifactHubPkg{}.install field

src/policy.rs, src/policy_artifacthub.rs, src/policy_metadata.rs
Adds in the Policy struct a new field to store the minimum version of the Kubewarden stack required to run the policy.
Fix #267 
```shell
make test
```
=> Minimum Kubewarden version field.

Cargo.toml
This is required to use latest version of sigstore
Once merged I'll tag a new release
=> chore(deps): update policy-fetcher

Cargo.toml, src/policy_evaluator.rs, src/policy_evaluator_builder.rs, src/runtimes/mod.rs, src/runtimes/wasi_cli/errors.rs, src/runtimes/wasi_cli/mod.rs, src/runtimes/wasi_cli/runtime.rs, src/runtimes/wasi_cli/stack.rs
Introduce a new type of policy execution mode: this runs WASI programs and leverages STDIN, STDOUT and STDERR as a way to communicate with the policy.
This allows policies written with the official Go compiler to be used. The Go compiler isn't able to produce WASM modules that `export` functions. This makes not possible the usage of waPC.
This is a known issue that is going to be addressed with future releases of the Go compiler. In the meantime, thanks to this PR, we will be able to write policies using the new Go compiler
=> feat: introduce WASI policies

Cargo.toml, crates/burrego/Cargo.toml
Update the following dependencies:
* wasmtime
* wasmtime-provider (used by wapc)
* policy-sdk-rust
* chrono: no update, but disable default features. This avoids the usage of the old and vulnerable time 0.1 crate
=> chore(deps): update dependencies

Cargo.toml
Use latest stable release of the kubewarden SDK. This release fixes an issue introduced by the prior release of the crate.
=> chore(deps): udpate kubewarden SDK

src/policy_evaluator_builder.rs, src/runtimes/wapc.rs
- fix: avoid allocation of callback channel: Neither the Rego, nor the WASI policies make use of host callbackes.
Hence, we can avoid to clone the callback channel required to interact
with the host.
- fix: avoid usage of `unwrap`: Avoid usage of unwrap when trying to acquire write/read access to the
waPC ReadWriteMutex. This kind of errors should not happen, but when
they do it would be better to bubble up the error instead of having a
panic.
- fix: implement cleanup for WapcStack: Remove from the WaPC policy mapping dictionary a policy that has been removed from the program stack.
=> Small cleanups

src/admission_request.rs, src/admission_response.rs, src/lib.rs, src/policy.rs, src/policy_evaluator.rs, src/policy_metadata.rs, src/runtimes/burrego.rs, src/runtimes/wapc.rs, src/runtimes/wasi_cli/runtime.rs
Change the policy evaluator and the existing runtimes to support "raw" policy requests.
Raw requests are generic requests that are not in the form of Kubernetes AdmissionRequests.
The AdmissionRequest type has been moved from the policy-server to this repo, which already contains the AdmissionResponse type.
The ValidatieRequest type has been refactored into an Enum type to support the new variant and runtimes have been changed accordingly.
The only exception is the Gatekeeper execution mode, being Gatekeeper k8s only by nature.
Note that we are still using the AdmissionResponse type as the return type of an evaluation since it is generic enough. The only difference is that we will not wrap it inside an AdmissionReview in the policy server if the user has requested a raw policy validation. …
=> feat: raw policy validation

src/policy_evaluator_builder.rs
Rewrote a unit test to avoid random failures. `cargo test` runs multiple tests in parallel, with a randomized order.
Under some circumstances, multiple wapc policies were defined at the same time, causing the hard coded expected values to fail.
The test has been rewritten to use different assertion criteria.
=> test: fix flaky unit test

src/callback_handler/kubernetes.rs, src/callback_handler/mod.rs, src/callback_requests.rs, src/policy_evaluator.rs, src/policy_evaluator_builder.rs, src/runtimes/mod.rs, src/runtimes/rego/context_aware.rs, src/runtimes/rego/gatekeeper_inventory.rs, src/runtimes/rego/mod.rs, src/runtimes/rego/opa_inventory.rs, src/runtimes/rego/runtime.rs, src/runtimes/rego/stack.rs, test_data/fixtures/kube_context/deployments/ingress/ingress-nginx.json, test_data/fixtures/kube_context/deployments/kube-system/coredns.json, test_data/fixtures/kube_context/deployments/kube-system/local-path-provisioner.json, test_data/fixtures/kube_context/namespaces/cert-manager.json, test_data/fixtures/kube_context/namespaces/kube-system.json, test_data/fixtures/kube_context/services/kube-system/kube-dns.json, test_data/fixtures/kube_context/services/kube-system/metrics-server.json
This PR allows Rego policies to be context aware.
No change to the API of the crate is done. No special action must be done by the consumers of this library.
Fixes: https://github.com/kubewarden/policy-evaluator/issues/353
=> rego context aware

src/policy_metadata.rs
Remove the extra quotes shown when displaying the policy type (raw/kubernetes).
Prior to this PR:
```console
policy type:                  "kubernetes"
```
After this PR:
```console
policy type:                  kubernetes
```
=> fix: pretty print of policy type

src/policy.rs, src/policy_artifacthub.rs, src/policy_evaluator_builder.rs, src/policy_metadata.rs, src/runtimes/rego/context_aware.rs, src/runtimes/rego/gatekeeper_inventory.rs, src/runtimes/rego/opa_inventory.rs, src/runtimes/rego/stack.rs
refactor: Make Rego inventories ordered with BTreeMap. This increases single access complexity, but we normally read all values.
This is to be consumed by kwctl for deterministic Rego context-aware inventories.
CI
=> refactor: Make Rego inventories deterministically ordered with BTreeMap

src/runtimes/rego/context_aware.rs, src/runtimes/rego/errors.rs, src/runtimes/rego/gatekeeper_inventory.rs, src/runtimes/rego/mod.rs, src/runtimes/rego/opa_inventory.rs, src/runtimes/rego/runtime.rs, src/runtimes/rego/stack.rs
Relates to https://github.com/kubewarden/policy-evaluator/issues/377
CI
This is one of the first PRs on this topic, deferring on changing the public policy-evaluator API until the refactor from https://github.com/kubewarden/kubewarden-controller/issues/528 is done.
=> refactor: use thiserror for internal errors of Rego module

Cargo.toml
Update to latest version of wamstime.
Note: I got a test failure locally, I think we have a flacky test. The test is however going to be removed by a PR that @fabriziosestito  is working on (the one that removes the locks on wapc)
=> Update to latest version of wasmtime

Cargo.toml, crates/burrego/Cargo.toml, src/evaluation_context.rs, src/policy_evaluator/mod.rs, src/policy_evaluator/policy_evaluator_builder.rs, src/policy_evaluator/policy_evaluator_pre.rs, src/runtimes.rs, src/runtimes/rego/errors.rs, src/runtimes/rego/mod.rs, src/runtimes/rego/runtime.rs, src/runtimes/rego/stack.rs, src/runtimes/rego/stack_pre.rs, src/runtimes/wapc/callback.rs, src/runtimes/wapc/mod.rs, src/runtimes/wapc/runtime.rs, src/runtimes/wapc/stack.rs, src/runtimes/wapc/stack_pre.rs, src/runtimes/wasi_cli/mod.rs, src/runtimes/wasi_cli/runtime.rs, src/runtimes/wasi_cli/stack.rs, src/runtimes/wasi_cli/stack_pre.rs
Introduce pre-initialized stack for all the types of policies that we currently support (Rego, waPC and WASI). These pre-initialized instance are managed by a high level resource called `PolicyEvaluatorPre`.
`PolicyEvaluatorPre` is created by `PolicyEvaluatorBuilder` once, then it can be used to create as many `PolicyEvaluator` instances as needed.
The `PolicyEvaluatorPre` instance is an immutable structure that can be safely shared across different threads once wrapped into a `Arc`.
This change is required to further reduce the memory usage of Policy Server, without compromising our performance.
Note: this PR is currently consuming a fork of waPC. I'm waiting for upstream to merge my PR.
=> feat: introduce `PolicyEvaluatorPre`

Cargo.toml, src/evaluation_context.rs
These changes are required by kwctl to consume latest version of policy-evaluator
- EvaluationContext: derive `Default` trait
- Patch bump: 0.13.3
=> unblock kwctl

src/errors.rs, src/policy_evaluator/evaluator.rs, src/runtimes/rego/errors.rs, src/runtimes/rego/stack_pre.rs, src/runtimes/wapc/errors.rs, src/runtimes/wapc/mod.rs, src/runtimes/wapc/runtime.rs, src/runtimes/wapc/stack.rs, src/runtimes/wapc/stack_pre.rs
Relates to https://github.com/kubewarden/policy-evaluator/issues/377.
- Partially implement thiserror a type and its enums for `crate::runtimes::wapc`.
It is still missing `crate::runtimes::wapc::callback` which will follow up later. The definition of the callback function [type is more complicated](https://github.com/kubewarden/policy-evaluator/blob/main/src/runtimes/wapc/callback.rs#L16), and I wanted to have a full codepath for the errors first.
- Finish migration to thiserror for `crate::runtimes::rego`. 
I recommend reviewing per commit, yet note that for `protocol_version()` there's a stopgap change between commits.
Note: `protocol_version()` is only consumed by kwctl but not yet by policy-server, opened https://github.com/kubewarden/policy-server/issues/642.
CI, integration tests.
=> refactor: Partially drop anyhow from `crate::runtimes:wapc`

src/runtimes/rego/errors.rs, src/runtimes/rego/gatekeeper_inventory.rs, src/runtimes/rego/opa_inventory.rs, src/runtimes/rego/runtime.rs, src/runtimes/rego/stack.rs, src/runtimes/wasi_cli/errors.rs, src/runtimes/wasi_cli/stack.rs, src/runtimes/wasi_cli/stack_pre.rs
Relates to https://github.com/kubewarden/policy-evaluator/issues/377
Opening this as draft for easy discussion.
Currently, it fails as it is expected that WasiRuntimeError can be converted from `std::result::Result<std::convert::Infallible, wasmtime::Error>`.
CI
=> refactor: Drop anyhow from wasi_cli

.github/workflows/tests.yml, .gitignore, Makefile, coverage/integration-tests/.gitignore, coverage/unit-tests/.gitignore
Add new make targets `coverage, `coverage-unit-tests`, `coverage-integration-tests` that are used in the CI. They run the tests via `cargo-tarpaulin` with llvm, and save the reports to the respective new folders `coverage/{unit-tests,integration-tests}/*`.
The make targets are both configured with `cargo +nightly`, as `cargo-tarpaulin` for the integration-tests need it, and in this way we can skip recompiling again. 
Add new CI job that runs the tests via the new makefile targets and uploads the result to codecov.
CI, PR should get a "welcome to codecov" message, and audit-scanner appear under https://app.codecov.io/github/kubewarden/.
=> ci: Add codecov support

Cargo.toml
This is a minor bump because we changed the way kubernetes resources are retrieved by context aware policies.
We now implement the "informer pattern", see https://github.com/kubewarden/kubewarden-controller/issues/575
Note: when 0.15.0 was tagged, the `Cargo.toml` file was **not** updated. That's why we are jumping from 0.14.x -> 0.16
=> Tag 0.16.0 release

.github/workflows/tests.yml
Updates the ci.yaml workflow file to use the new github action created to install the cargo tarpaulin.
Related to  https://github.com/kubewarden/kubewarden-controller/issues/667
=> chore: use tarpaulin-install action to install tarpaulin.

Cargo.toml, crates/burrego/examples/cli/main.rs, crates/burrego/src/errors.rs, crates/burrego/src/evaluator.rs, crates/burrego/src/policy.rs, crates/burrego/src/stack_helper.rs, src/callback_handler.rs, src/callback_handler/kubernetes.rs, src/callback_handler/kubernetes/client.rs, src/callback_handler/kubernetes/reflector.rs, src/callback_requests.rs, src/runtimes/rego/context_aware.rs, src/runtimes/rego/errors.rs, src/runtimes/rego/gatekeeper_inventory.rs, src/runtimes/rego/gatekeeper_inventory_cache.rs, src/runtimes/rego/mod.rs, src/runtimes/rego/runtime.rs, src/runtimes/rego/stack.rs
Cache the serialized version of a Gatekeeper policy for later reuse. This is going to reduce the evaluation time of Gatekeeper policy that make use of context aware data.
Fixes https://github.com/kubewarden/policy-server/issues/704
=> gatekeeper inventory optimization

Cargo.toml
Create the 0.16.3 release, this is required to fix some build issues with policy-server and kwctl
=> Tag new patch release

src/callback_requests.rs
Previously, the `Serialize` and `Deserialize` traits have been removed from the `CallbackRequestType`. That was done because the `tokio::time::Instant` trait doesn't derive them.
I initially though we didn't need these traits to be provided by this object. That proved true because I was working only on Policy Server, which doesn't require them.
However, kwctl requires them to save and restore context aware sessions.
This commit introduces custom serializer and deserializer functions for `tokio::time::Instant`, making possible to reintroduce the `Serialize` and `Deserialize` traits. This fixes the compilation of kwctl.
=> fix: allow kwctl to build using latest version of this crate

Cargo.toml, src/callback_handler/builder.rs, src/callback_handler/sigstore_verification.rs, tests/integration_test.rs
The Sigstore project changed the internals of its TUF repository, which broke sigstore-rs.
This commit updates to the latest version of sigstore-rs. The code changes have been caused by the massive changes done by sigstore-rs.
Required to fix https://github.com/kubewarden/kwctl/issues/753
=> fix: address changes done to Sigstore TUF repository

src/callback_handler/kubernetes/reflector.rs, tests/integration_test.rs, tests/k8s_mock/mod.rs
This is a "backport" of a fix that will be included as a part of:  https://github.com/kubewarden/policy-server/issues/716
Fixes #489 
Improves wapc/wasi integration tests by adding the right watch mock API response.
Also, it adds a scenario to test the reflector initialization error.
In this implementation we are just circuit-breaking the stream, this means a generic error will be returned to the client.
This is a temporary trade-off since we are still using the default `Writer` from `kube-rs` which has its ready channel.
In `1.13` we will implement our custom writer, and the ready channel will be extended to return a result, therefore the user will receive a custom error.
=> fix: reflector initial list error handling

src/callback_handler/kubernetes/reflector.rs, tests/integration_test.rs, tests/k8s_mock/mod.rs
Fix: #498 
This PR reverts breaking the watcher stream if the Initial list cannot be fetched (#490).
We are not reverting the entire PR because we want to keep some work on the integration tests that is still valuable.
This was causing long response times when a policy was initializing a reflect that was never started before, causing the timeout protection to kill the policy.
In the future we could consider moving away from the lazy initialization and starting the reflectors when the policy server start as proposed in [this rfc](https://github.com/kubewarden/rfc/blob/main/rfc/0019-reflectors-database-cache.md#sqlite-database-store).
=> fix: revert break reflector stream on InitialListFailed error

Cargo.toml
Update wasmtime and wapc-wasmtime to latest version.
Some notes:
- wasmtime version is constrained by wapc-wasmtime
- wapc-wasmtime is not using the latest stable release of wasmtime, because this just came out. I've made a PR to bump that, in the meantime we should just upgrade
- we cannot consume wapc-wasmtime from crates.io. We (wapc maintainers) lost access to it. Only a former maintainer has access to it. We're working to solve the issue. In the meantime we have to consume this dependency by using the git tag.
=> chore(deps): update wapc and wasmtime

Cargo.toml
Switches to a patched revision of kube-rs (forked) that includes the stream buffering fix.
See https://github.com/kube-rs/kube/pull/1494 and https://github.com/kube-rs/kube/issues/1487
This is needed since the PR was not yet merged and we need to release v1.13.0-rc1
=> build(deps): use kube-rs reduce buffering rev

src/callback_handler/kubernetes/reflector.rs
Clears `"kubectl.kubernetes.io/last-applied-configuration"` annotation to reduce memory usage.
=> fix: clear last-applied-configuration annotation to reduce memory usage

Cargo.toml
Fixes `kube-rs` dependency (fork) that was pointing to a rev that does not exist anymore.
Bumps Cargo.toml to v0.17.4
=> fix(deps): fix kube-rs fork dependency 

Cargo.toml, src/callback_handler.rs, src/callback_handler/oci.rs, src/callback_requests.rs, tests/integration_test.rs
Adds a new host capability to allow guest to request an OCI image manifest, its digest and configuration.
Fix #518 
```shell
make test
```
=> feat: get OCI image manifest and configuration.

src/runtimes/callback.rs
The policy-evaluator is missing the mapping of the callback to the recent added capability to get container image manifest and config. This commit fix that adding the missing match arm in the callbacks.rs file.
Related to https://github.com/kubewarden/kubewarden-controller/issues/749
=> fix: missing callback for new capability.

Cargo.toml
Updates the policy-evaluator to v0.18.3 version.
=> chore: bump version v0.18.3.

src/admission_request.rs
Derive the `Eq` and `PartialEq` traits. These are useful when writing assertions inside of unit tests.
=> feat: GroupVersionKind and GroupVersionResource derive extra traits

Cargo.toml, src/callback_handler/oci.rs, src/policy_artifacthub.rs, tests/integration_test.rs
The `oci-distribution` create has been renamed
=> chore(deps): rename oci-distribution to oci-client

src/admission_response.rs, tests/integration_test.rs
Implement all the fields that are part of an AdmissionResponse object.
While doing that I also cleaned up a bit our code. I've turned some `String` into `enums` and I've added some inline documentation by doing copy and paste from the Kubernetes' one.
Note: we cannot rely on `k8s-openapi` for these Rust structs since they are not part of the OpenAPI definitions of Kubernetes.
=> feat: full implementation of AdmissionResponse object

src/callback_handler/oci.rs, src/runtimes/rego/runtime.rs, src/runtimes/wapc/runtime.rs, src/runtimes/wasi_cli/runtime.rs, tests/integration_test.rs
The `OciManifestDigest` response returns the digest as a JSON string since it was erroneously encoded to JSON in the callback handler.
This PR removes the extra encoding returning a plain string.
Test was missing, added
=> fix: return digest as plain string instead of a json string 

Cargo.toml
Bumps crate to version 0.19.7.
=> chore: v0.19.7 version bump.

Cargo.toml
The policies built with tinygo >= 0.35.0 failed to run.
The issue was inside of the wasmtime-provider of the wapc project.
This commit updates to a version of the crate that fixes the problem.
=> fix: tinygo 0.35.0 policies exit at startup

renovate.json
Updates the renovate bot configuration to bump wasmtime-wasi, wasmtime and wasi-common crates versions together.
=> build(deps): group wasmtime crates updates together.

Cargo.toml
The contents of Sigstore's TUF repository have been recently changed and, due to a mistake, the sigstore-rs was broken.
This commit consumes a forked version of sigstore-rs, which consumes a forked version of the tough crate.
This is required to fix https://github.com/sigstore/sigstore-rs/issues/429 until upstream changes the contents of TUF's repository.
=> fix: address broken sigstore's TUF repository

Cargo.toml
=> chore: bump version to v0.19.10

Cargo.toml, src/callback_handler/sigstore_verification.rs, src/callback_requests.rs
Upgrade to latest verison of sigstore by consuming latest releaes of policy-evaluator.
We must use latest version of the Kubewarden SDK too to have the code compile.
=> chore(deps): update sigstore

.taplo.toml, Cargo.toml, src/policy_artifacthub.rs, src/policy_metadata.rs
All the annotations are now using BTreeMap instead of HashMap, this makes everything simpler when dealing with OCI annotations (which use this data structure).
This is part of the work required to implement https://github.com/kubewarden/kwctl/issues/1044
While working on this PR, I've added a taplo configuration file to the repository, this will help us to keep the Cargo.toml file nice and tidy.
=> refactor annotations

src/policy_artifacthub.rs
Introduces the `gh_release_tag` parameter, allowing customization of the release tag name when constructing download links in `artifacthub-pkg.yml`.  
For example:  
- Without overriding the release tag for `repo` policy v0.2.1:  
`https://github.com/repo/releases/download/v0.2.1/policy.wasm`  
- With `gh_release_tag` set to `SomePolicy/v0.2.1`:  
`https://github.com/repo/releases/download/SomePolicy%2Fv0.2.1/policy.wasm`  
This is particularly useful when working with repositories like [kubewarden/rego-policies-library](https://github.com/kubewarden/rego-policies-library/) or any repository where release names do not strictly follow semantic versioning.
=> feat: add gh release tag to ArtifactHubPkg

src/constants.rs, src/policy_artifacthub.rs
Introduce a new annotation to keep track of a policy version: `io.kubewarde.policy.version`.
This annotation is then required when scaffolding the `artifacthub-pkg.yaml` file.
Required to fix https://github.com/kubewarden/kwctl/issues/1137
=> feat: introduce policy version annotation

src/constants.rs, src/policy_artifacthub.rs
Add a new annotation to configure the github release tag. This information is used when scaffolding the artifacthub-pkg file.
Related with https://github.com/kubewarden/kwctl/issues/1137
=> feat: add new annotation

.github/workflows/tests.yml
Removes the deprecated actions-rs/cargo Github action used to run cargo commands.
Related to https://github.com/kubewarden/kubewarden-controller/issues/1092
=> fix: remove deprecated actions-rs/cargo Github action.

Cargo.toml
Updates the version of the policy-evaluator to release the k8s-openapi update.
=> chore: bump v0.25.2 version.

Cargo.toml, src/policy_evaluator.rs, src/policy_evaluator/policy_evaluator_builder.rs, src/policy_group_evaluator.rs, src/policy_group_evaluator/evaluator.rs, src/runtimes/rego/runtime.rs, tests/common/mod.rs, tests/integration_test.rs
These are some changes required to implement the `kwctl run <group>` feature (see https://github.com/kubewarden/kwctl/issues/967).
Once merged, a new version of policy-evaluator should be tagged
- **refactor(test): do not use deprecated code**
- **refactor: address linter warning**
- **feat: implement `TryInto` to convert SDKs ojects**
=> kwctl policy group changes

Cargo.toml, src/runtimes/wasi_cli/stack_pre.rs
Update to latest stable version of `wasmtime`, also update `wasmtime-provider`.
Fix some issues caused by API changes.
**WARNING:** this is currently blocked because:
- we need https://github.com/wapc/wapc-rs/pull/153 to be merged, plus a new release of `wasmtime-provider` must be created
- we need to wait for Kubewarden 1.26 to be released
=> chore(deps): update wasmtime

Cargo.toml, src/admission_response_handler.rs, src/admission_response_handler/policy_mode.rs
Part of https://github.com/kubewarden/kwctl/issues/1272
Changes needed  by `kwctl::config::policy_definition::PolicyDefinition`, which will from now on
include `PolicyMode`.
CI. See other PRs.
=> refactor: Needed for kwctl functionality

src/runtimes/wasi_cli/stack_pre.rs
> This is a DRAFT PR: we have to decide how we want to solve this problem, an alternative solution is the one of PR https://github.com/kubewarden/kwctl/pull/1388
Our JavaScript/TypeScript policies are written using the Javy compiler and they necessitate a custom Javy pluging to work.
The Javy plugin defines some functions used by the js VM, plus it imports the usual `host:call` function from the WebAssembly host.
Everything was working fine until the javy-plugin version `4.0.0` was released.
This release requires to build our plugin using the wasip2 target, which in turns forces the usage of the WebAssembly component model. However, at this time, the javy compiler (v7.0.0) produces wasip1 modules instead of wasm components.
Among other changes, unrelated to this commit, the intermediate …
=> fix: allow js policies built by latest javy compiler to work
