Cargo.lock
Cargo.toml
src/policy_metadata.rs

Add the `annotations` field to the policy metadata

Metadata annotations

---

crates/burrego/src/main.rs
crates/burrego/src/opa/default_host_callbacks.rs
crates/burrego/src/opa/host_callbacks.rs
crates/burrego/src/opa/mod.rs
crates/burrego/src/opa/wasm.rs
src/lib.rs
src/policy_evaluator.rs
src/runtimes/burrego.rs
src/runtimes/wapc.rs

Fixes https://github.com/kubewarden/policy-evaluator/issues/23

User provided host functions

---

crates/burrego/src/opa/builtins/debugging.rs
crates/burrego/src/opa/builtins/mod.rs

Fixes https://github.com/kubewarden/policy-evaluator/issues/53

Implement debugging builtins

---

src/policy_evaluator.rs

Sometimes the tests accessing the `WAPC_POLICY_MAPPING` hash didn't work as expected.
That happened because `cargo test` can run tests in parallel, and that could lead to corner cases where the two tests working against this static hash broke each other.
I changed the way the tests check for the behaviour to avoid any flakyness.

Fix flaky test

---

Cargo.toml
src/cluster_context.rs

This is required to fix https://github.com/kubewarden/kwctl/issues/86
Currently in draft, the API of `kube` change and it breaks building

Upgrade to the lastest version of tokio

---

Cargo.toml

Ensure openssl-sys is not pulled in as a dependency of this library

Version bump 0.2.7

---

crates/burrego/Cargo.toml
crates/burrego/src/main.rs

Update to latest version of clap

burrego cli: update to latest clap

---

src/validation_response.rs

chore: Implement Eq and PartialEq for ValidationResponse

chore: Implement Eq and PartialEq for ValidationResponse

---

Cargo.toml
src/policy_evaluator.rs

* Update some dependencies, most notable one: policy-fetcher
* Remove the explicit dependency on `oci-distribution`, this wasn't used anymore

Version bump 0.2.14

---

Cargo.toml

bump policy-evaluator version to 0.2.17
bump policy-fetcher version to 0.6.1

bump policy-evaluator and policy-fetcher versions

---

Cargo.toml

Use latest sigstore-rs to fix https://github.com/kubewarden/verify-image-signatures/issues/20

bump policy-fetcher to v0.7.8

---

Cargo.toml
src/callback_handler/mod.rs
src/callback_handler/oci.rs
src/callback_handler/sigstore_verification.rs

feat: use docker_credential crate instead of DockerConfig

---

Cargo.toml
src/lib.rs
src/policy_evaluator.rs

- feat: expose kubewarden-policy-sdk crate
- feat: introduce `Evaluator` trait
- Patch release 0.4.18

small enhancements

---

.github/workflows/tests.yml
Cargo.toml
Makefile
crates/burrego/Cargo.toml

chore: update rust edition

---

Cargo.toml

- chore(deps): update policy-fetcher
- Tag v0.6.1
This is required to fix https://github.com/kubewarden/policy-fetcher/issues/131
I'll tag a new version once this PR gets merged

update policy fetcher

---

Cargo.toml
crates/burrego/Cargo.toml

Upgrade wapc and wasmtime to latest version.

chore(deps: update wasmtime

---

src/callback_handler/kubernetes.rs
src/callback_handler/mod.rs
src/callback_requests.rs
src/runtimes/wapc.rs

Allow a specific Kubernetes resource to be searched.

feat: expand the context aware API

---

src/constants.rs
src/policy_artifacthub.rs
src/policy_evaluator.rs
src/policy_metadata.rs

Update artifact hub metadata to reflect the changes done to context aware policies.

context aware: fix artifact hub metadata

---

Cargo.toml
crates/burrego/Cargo.toml

Version bump: 0.9.2

---

Cargo.toml
crates/burrego/Cargo.toml

Use latest stable release of wasmtime

chore(deps): update wasmtime

---

src/constants.rs

Relates to https://github.com/kubewarden/kwctl/issues/529
No need.

feat: Add constants for policy severity and category annots

---

Cargo.toml
src/constants.rs

Relates to https://github.com/kubewarden/policy-evaluator/pull/294
Needed to bump and release audit-scanner.
Local make test, CI.

build: Bump version to 0.11.0 

---

Cargo.toml

Use latest version of policy-fetcher

chore(deps): bump policy-fetcher

---

.github/workflows/tests.yml

Express all the dependencies using their full version

chore(deps): fix GH action dependencies

---

Cargo.toml

Use latest stable version of wasmtime

chore(deps): update to latest version of wasmtime

---

src/policy_artifacthub.rs
src/policy_metadata.rs

Adds `policyType` (kubernetes/raw, defaults to kubernetes) to the Policy metadata.
yes

feat: add policy type to metadata

---

Cargo.toml

chore: bump version to v0.12.0

---

Cargo.toml
src/policy_metadata.rs

implement Display and add PartialEq to policy_metadata::PolicyType.
It also prepares the 0.12.1 release.

fix: implement Display and add PartialEq to policy_metadata::PolicyType

---

Cargo.toml

chore: bump version to v0.12.2

---

Cargo.toml

Allow Wasi policy to invoke host capabilities

Tag 0.14.0 release

---

src/callback_handler/kubernetes.rs

Since `kube::core::ObjectList` was not implementing the `Clone` trait, we used to have this custom `ObjectList` struct.
Since kube 0.88.1 this is no longer needed

refactor: remove ObjectList

---

Cargo.toml
crates/burrego/Cargo.toml
crates/burrego/src/host_callbacks.rs
src/admission_response.rs
src/callback_handler.rs
src/errors.rs
src/policy_artifacthub.rs
src/policy_evaluator.rs
src/policy_evaluator/errors.rs
src/policy_evaluator/policy_evaluator_builder.rs
src/policy_evaluator/policy_evaluator_pre.rs
src/policy_metadata.rs
src/runtimes/rego/mod.rs
src/runtimes/wapc/runtime.rs
src/runtimes/wasi_cli/mod.rs

Fix https://github.com/kubewarden/policy-evaluator/issues/377
Provide new typed errors: `MetadataError`, `ResponseError`, `PolicyEvaluatorPreError`, `PolicyEvaluatorBuilderError`, and return them in their respective public functions.
CI

feat!: Provide typed errors for public functions

---

Cargo.toml
src/runtimes/wasi_cli/stack.rs

Update to latest version of wasmtime.

chore(deps) Update wasmtime

---

src/runtimes/callback.rs
src/runtimes/rego/context_aware.rs
tests/integration_test.rs

Reduce the amount of CPU used by policies with host capabilities. This is will reduce the latency of evaluating certain types of policies.
Part of the efforts to fix https://github.com/kubewarden/policy-server/issues/692

fix: reduce CPU required by policies with host capabilities

---

Cargo.toml

chore: bump version to v0.16.2

---

Cargo.toml

Update dependencies, fix kwctl building process

Tag v0.16.4

---

Cargo.toml

chore: prepare for v0.17.2 release

---

Cargo.toml

chore: prepare for v0.17.3 release

---

Cargo.toml

- **chore(deps): update wapc and wasmtime**
- **Tag new patch release**

update wapc and wasmtime

---

src/runtimes/wasi_cli/errors.rs
src/runtimes/wasi_cli/runtime.rs
src/runtimes/wasi_cli/stack.rs

fix: WASI runtime rejection response

---

Cargo.toml

chore: bump version to v0.17.7

---

src/policy_metadata.rs

Implment `TryFrom` traits for `Operation` and `NamedRuleWithOperation` to smooth the conversion from Kubernetes native types.
This is required to implement the scaffolding from VAP to Kubewarden policies.

feat: implement `TryFrom` traits

---

Cargo.toml

Reverts kube-rs dependency to upstream, bumping the version to v0.92.1

build(deps): revert kube-rs dependency to upstream

---

Cargo.toml

Update to latest stable release of wasmtime

chore(deps): bump wasmtime

---

Cargo.toml

Bump policy-fetcher dependency

Prepare 0.19.6 release

---

Cargo.toml

Updates several dependencies and reverts a wasmtime library update to keep all the crates in the same version until it's possible to bump all together.

chore(deps): fix dependencies

---

Cargo.toml

Update to latest stable release and tag a new patch release.
Once this is merged I'll tag a new release

chore(deps): update wasmtime and wapc

---

.github/workflows/tests.yml
.typos.toml
Makefile
crates/burrego/src/stack_helper.rs
src/callback_handler/crypto.rs
src/policy_evaluator.rs
src/runtimes/rego/stack_pre.rs
tests/data/endless_wasm/README.md
tests/data/endless_wasm/wapc_endless_loop.wat

Use `crate-ci/typos` to detect typos

test: check typos

---

Cargo.toml

chore: bump version to v0.21.0

---

Cargo.toml

build: Bump version to v0.23.0

---

renovate.json

Fix #661
To test this pull request, you can run the following commands:

fix: Update dependency wasmtime packages

---

Cargo.toml

build: Bump version to 0.25.0

---

.github/workflows/tests.yml
.github/workflows/update-rust-toolchain.yaml
rust-toolchain.toml
updatecli/DEVELOP.md
updatecli/updatecli.d/update-rust-toolchain.yaml
updatecli/values.yaml

Adds the rust-toolchain.toml file to configure the build command on witch toolchain and target it should use.
Related to https://github.com/kubewarden/kubewarden-controller/issues/1093

chore(deps): add rust-toolchain.toml.

---

Cargo.toml

Update a bunch of dependencies to latest version, prepare to tag a new release.

chore(deps): update dependencies

---

src/policy_evaluator.rs
src/policy_evaluator/policy_evaluator_pre.rs
src/policy_evaluator/stack_pre.rs
src/policy_group_evaluator/evaluator.rs
src/runtimes.rs
src/runtimes/wasi_cli/wasi_pipe.rs
tests/integration_test.rs

Fix linter errors in the code.

fix(linter): fix clippy errors.

---

Cargo.toml
src/lib.rs

Part of https://github.com/kubewarden/kwctl/issues/1290.
Not tested e2e with kwctl, having trouble building locally.

deps: Consume kubewarden-policy-sdk 0.14.3

---

Cargo.toml

Needed by https://github.com/kubewarden/kwctl/pull/1311

build: Bump version to 0.29.2
